Create CODE-OF-CONDUCT.md
input-output-hk/cardano-prelude pull request #178
Opened 2022-11-03 16:32 UTC by Trueblueaddie

This is a requested document for the repos going to the MBO. It follows a standard format.

2023-01-02 16:48 UTC, coot requested changes
We link to _Cardano Engineering Handbook` in other repos (e.g. `ouroboros-network`, `cardano-node`, `cardano-ledger` and probably `plutus` too).

2023-01-02 16:48 UTC, coot commented on CODE-OF-CONDUCT.md
> +[homepage]: https://www.contributor-covenant.org
```suggestion
See https://github.com/input-output-hk/cardano-engineering-handbook/blob/main/CODE-OF-CONDUCT.md
```

We link to `cardano-engineerng-handbook` in `cardano-node`, `ourobos-network`, `cardano-ledger` and maybe even `plutus` repos.

2023-01-06 21:27 UTC, Trueblueaddie commented
thanks, modified, let me know if there are further steps to take.

2023-01-09 09:59 UTC, coot approved these changes

2023-01-12 10:57 UTC, merged